//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package upstreamv1beta4

import (
	unsafe "unsafe"

	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta2 "sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1beta2.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(a.(*APIEndpoint), b.(*v1beta2.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(a.(*v1beta2.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Arg)(nil), (*v1beta2.Arg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Arg_To_v1beta2_Arg(a.(*Arg), b.(*v1beta2.Arg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Arg)(nil), (*Arg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Arg_To_upstreamv1beta4_Arg(a.(*v1beta2.Arg), b.(*Arg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootstrapTokenDiscovery)(nil), (*v1beta2.BootstrapTokenDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BootstrapTokenDiscovery_To_v1beta2_BootstrapTokenDiscovery(a.(*BootstrapTokenDiscovery), b.(*v1beta2.BootstrapTokenDiscovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BootstrapTokenDiscovery)(nil), (*BootstrapTokenDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BootstrapTokenDiscovery_To_upstreamv1beta4_BootstrapTokenDiscovery(a.(*v1beta2.BootstrapTokenDiscovery), b.(*BootstrapTokenDiscovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootstrapTokenString)(nil), (*v1beta2.BootstrapTokenString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BootstrapTokenString_To_v1beta2_BootstrapTokenString(a.(*BootstrapTokenString), b.(*v1beta2.BootstrapTokenString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BootstrapTokenString)(nil), (*BootstrapTokenString)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BootstrapTokenString_To_upstreamv1beta4_BootstrapTokenString(a.(*v1beta2.BootstrapTokenString), b.(*BootstrapTokenString), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BottlerocketBootSettings)(nil), (*v1beta2.BottlerocketBootSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketBootSettings_To_v1beta2_BottlerocketBootSettings(a.(*BottlerocketBootSettings), b.(*v1beta2.BottlerocketBootSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BottlerocketBootSettings)(nil), (*BottlerocketBootSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketBootSettings_To_upstreamv1beta4_BottlerocketBootSettings(a.(*v1beta2.BottlerocketBootSettings), b.(*BottlerocketBootSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BottlerocketBootstrap)(nil), (*v1beta2.BottlerocketBootstrap)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(a.(*BottlerocketBootstrap), b.(*v1beta2.BottlerocketBootstrap), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BottlerocketBootstrap)(nil), (*BottlerocketBootstrap)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(a.(*v1beta2.BottlerocketBootstrap), b.(*BottlerocketBootstrap), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BottlerocketKernelSettings)(nil), (*v1beta2.BottlerocketKernelSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketKernelSettings_To_v1beta2_BottlerocketKernelSettings(a.(*BottlerocketKernelSettings), b.(*v1beta2.BottlerocketKernelSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BottlerocketKernelSettings)(nil), (*BottlerocketKernelSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketKernelSettings_To_upstreamv1beta4_BottlerocketKernelSettings(a.(*v1beta2.BottlerocketKernelSettings), b.(*BottlerocketKernelSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BottlerocketKubernetesSettings)(nil), (*v1beta2.BottlerocketKubernetesSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings(a.(*BottlerocketKubernetesSettings), b.(*v1beta2.BottlerocketKubernetesSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BottlerocketSettings)(nil), (*v1beta2.BottlerocketSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(a.(*BottlerocketSettings), b.(*v1beta2.BottlerocketSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BottlerocketSettings)(nil), (*BottlerocketSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(a.(*v1beta2.BottlerocketSettings), b.(*BottlerocketSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CertBundle)(nil), (*v1beta2.CertBundle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_CertBundle_To_v1beta2_CertBundle(a.(*CertBundle), b.(*v1beta2.CertBundle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.CertBundle)(nil), (*CertBundle)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_CertBundle_To_upstreamv1beta4_CertBundle(a.(*v1beta2.CertBundle), b.(*CertBundle), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvVar)(nil), (*v1beta2.EnvVar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_EnvVar_To_v1beta2_EnvVar(a.(*EnvVar), b.(*v1beta2.EnvVar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EnvVar)(nil), (*EnvVar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EnvVar_To_upstreamv1beta4_EnvVar(a.(*v1beta2.EnvVar), b.(*EnvVar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalEtcd)(nil), (*v1beta2.ExternalEtcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_ExternalEtcd_To_v1beta2_ExternalEtcd(a.(*ExternalEtcd), b.(*v1beta2.ExternalEtcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ExternalEtcd)(nil), (*ExternalEtcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ExternalEtcd_To_upstreamv1beta4_ExternalEtcd(a.(*v1beta2.ExternalEtcd), b.(*ExternalEtcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileDiscovery)(nil), (*v1beta2.FileDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_FileDiscovery_To_v1beta2_FileDiscovery(a.(*FileDiscovery), b.(*v1beta2.FileDiscovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostPathMount)(nil), (*v1beta2.HostPathMount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_HostPathMount_To_v1beta2_HostPathMount(a.(*HostPathMount), b.(*v1beta2.HostPathMount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.HostPathMount)(nil), (*HostPathMount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_HostPathMount_To_upstreamv1beta4_HostPathMount(a.(*v1beta2.HostPathMount), b.(*HostPathMount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.JoinControlPlane)(nil), (*JoinControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane(a.(*v1beta2.JoinControlPlane), b.(*JoinControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Mirror)(nil), (*v1beta2.Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Mirror_To_v1beta2_Mirror(a.(*Mirror), b.(*v1beta2.Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Mirror)(nil), (*Mirror)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Mirror_To_upstreamv1beta4_Mirror(a.(*v1beta2.Mirror), b.(*Mirror), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Patches)(nil), (*v1beta2.Patches)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Patches_To_v1beta2_Patches(a.(*Patches), b.(*v1beta2.Patches), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Patches)(nil), (*Patches)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Patches_To_upstreamv1beta4_Patches(a.(*v1beta2.Patches), b.(*Patches), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Pause)(nil), (*v1beta2.Pause)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Pause_To_v1beta2_Pause(a.(*Pause), b.(*v1beta2.Pause), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Pause)(nil), (*Pause)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Pause_To_upstreamv1beta4_Pause(a.(*v1beta2.Pause), b.(*Pause), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProxyConfiguration)(nil), (*v1beta2.ProxyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_ProxyConfiguration_To_v1beta2_ProxyConfiguration(a.(*ProxyConfiguration), b.(*v1beta2.ProxyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ProxyConfiguration)(nil), (*ProxyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_ProxyConfiguration(a.(*v1beta2.ProxyConfiguration), b.(*ProxyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegistryMirrorConfiguration)(nil), (*v1beta2.RegistryMirrorConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(a.(*RegistryMirrorConfiguration), b.(*v1beta2.RegistryMirrorConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RegistryMirrorConfiguration)(nil), (*RegistryMirrorConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(a.(*v1beta2.RegistryMirrorConfiguration), b.(*RegistryMirrorConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*APIServer)(nil), (*v1beta2.APIServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_APIServer_To_v1beta2_APIServer(a.(*APIServer), b.(*v1beta2.APIServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BootstrapToken)(nil), (*v1beta2.BootstrapToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BootstrapToken_To_v1beta2_BootstrapToken(a.(*BootstrapToken), b.(*v1beta2.BootstrapToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BottlerocketAdmin)(nil), (*v1beta2.BottlerocketAdmin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketAdmin_To_v1beta2_BottlerocketAdmin(a.(*BottlerocketAdmin), b.(*v1beta2.BottlerocketAdmin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BottlerocketBootstrapContainer)(nil), (*v1beta2.BottlerocketBootstrapContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketBootstrapContainer_To_v1beta2_BottlerocketBootstrapContainer(a.(*BottlerocketBootstrapContainer), b.(*v1beta2.BottlerocketBootstrapContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BottlerocketControl)(nil), (*v1beta2.BottlerocketControl)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketControl_To_v1beta2_BottlerocketControl(a.(*BottlerocketControl), b.(*v1beta2.BottlerocketControl), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*BottlerocketHostContainer)(nil), (*v1beta2.BottlerocketHostContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_BottlerocketHostContainer_To_v1beta2_BottlerocketHostContainer(a.(*BottlerocketHostContainer), b.(*v1beta2.BottlerocketHostContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ClusterConfiguration)(nil), (*v1beta2.ClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_ClusterConfiguration_To_v1beta2_ClusterConfiguration(a.(*ClusterConfiguration), b.(*v1beta2.ClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ControlPlaneComponent)(nil), (*v1beta2.ControllerManager)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_ControlPlaneComponent_To_v1beta2_ControllerManager(a.(*ControlPlaneComponent), b.(*v1beta2.ControllerManager), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ControlPlaneComponent)(nil), (*v1beta2.Scheduler)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_ControlPlaneComponent_To_v1beta2_Scheduler(a.(*ControlPlaneComponent), b.(*v1beta2.Scheduler), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*DNS)(nil), (*v1beta2.DNS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_DNS_To_v1beta2_DNS(a.(*DNS), b.(*v1beta2.DNS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Discovery)(nil), (*v1beta2.Discovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Discovery_To_v1beta2_Discovery(a.(*Discovery), b.(*v1beta2.Discovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Etcd)(nil), (*v1beta2.Etcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Etcd_To_v1beta2_Etcd(a.(*Etcd), b.(*v1beta2.Etcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*InitConfiguration)(nil), (*v1beta2.InitConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_InitConfiguration_To_v1beta2_InitConfiguration(a.(*InitConfiguration), b.(*v1beta2.InitConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*JoinConfiguration)(nil), (*v1beta2.JoinConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_JoinConfiguration_To_v1beta2_JoinConfiguration(a.(*JoinConfiguration), b.(*v1beta2.JoinConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*JoinControlPlane)(nil), (*v1beta2.JoinControlPlane)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_JoinControlPlane_To_v1beta2_JoinControlPlane(a.(*JoinControlPlane), b.(*v1beta2.JoinControlPlane), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*LocalEtcd)(nil), (*v1beta2.LocalEtcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_LocalEtcd_To_v1beta2_LocalEtcd(a.(*LocalEtcd), b.(*v1beta2.LocalEtcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*NodeRegistrationOptions)(nil), (*v1beta2.NodeRegistrationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOptions(a.(*NodeRegistrationOptions), b.(*v1beta2.NodeRegistrationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Proxy)(nil), (*v1beta2.ProxyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Proxy_To_v1beta2_ProxyConfiguration(a.(*Proxy), b.(*v1beta2.ProxyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*Timeouts)(nil), (*v1beta2.Timeouts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_upstreamv1beta4_Timeouts_To_v1beta2_Timeouts(a.(*Timeouts), b.(*v1beta2.Timeouts), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.APIServer)(nil), (*APIServer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_APIServer_To_upstreamv1beta4_APIServer(a.(*v1beta2.APIServer), b.(*APIServer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BootstrapToken)(nil), (*BootstrapToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BootstrapToken_To_upstreamv1beta4_BootstrapToken(a.(*v1beta2.BootstrapToken), b.(*BootstrapToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BottlerocketAdmin)(nil), (*BottlerocketAdmin)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketAdmin_To_upstreamv1beta4_BottlerocketAdmin(a.(*v1beta2.BottlerocketAdmin), b.(*BottlerocketAdmin), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BottlerocketBootstrapContainer)(nil), (*BottlerocketBootstrapContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketBootstrapContainer_To_upstreamv1beta4_BottlerocketBootstrapContainer(a.(*v1beta2.BottlerocketBootstrapContainer), b.(*BottlerocketBootstrapContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BottlerocketControl)(nil), (*BottlerocketControl)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketControl_To_upstreamv1beta4_BottlerocketControl(a.(*v1beta2.BottlerocketControl), b.(*BottlerocketControl), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BottlerocketHostContainer)(nil), (*BottlerocketHostContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketHostContainer_To_upstreamv1beta4_BottlerocketHostContainer(a.(*v1beta2.BottlerocketHostContainer), b.(*BottlerocketHostContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.BottlerocketKubernetesSettings)(nil), (*BottlerocketKubernetesSettings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BottlerocketKubernetesSettings_To_upstreamv1beta4_BottlerocketKubernetesSettings(a.(*v1beta2.BottlerocketKubernetesSettings), b.(*BottlerocketKubernetesSettings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.ClusterConfiguration)(nil), (*ClusterConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterConfiguration_To_upstreamv1beta4_ClusterConfiguration(a.(*v1beta2.ClusterConfiguration), b.(*ClusterConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.ControllerManager)(nil), (*ControlPlaneComponent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ControllerManager_To_upstreamv1beta4_ControlPlaneComponent(a.(*v1beta2.ControllerManager), b.(*ControlPlaneComponent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.DNS)(nil), (*DNS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_DNS_To_upstreamv1beta4_DNS(a.(*v1beta2.DNS), b.(*DNS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.Discovery)(nil), (*Discovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Discovery_To_upstreamv1beta4_Discovery(a.(*v1beta2.Discovery), b.(*Discovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.Etcd)(nil), (*Etcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Etcd_To_upstreamv1beta4_Etcd(a.(*v1beta2.Etcd), b.(*Etcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.FileDiscovery)(nil), (*FileDiscovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FileDiscovery_To_upstreamv1beta4_FileDiscovery(a.(*v1beta2.FileDiscovery), b.(*FileDiscovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.InitConfiguration)(nil), (*InitConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_InitConfiguration_To_upstreamv1beta4_InitConfiguration(a.(*v1beta2.InitConfiguration), b.(*InitConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.JoinConfiguration)(nil), (*JoinConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_JoinConfiguration_To_upstreamv1beta4_JoinConfiguration(a.(*v1beta2.JoinConfiguration), b.(*JoinConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.LocalEtcd)(nil), (*LocalEtcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_LocalEtcd_To_upstreamv1beta4_LocalEtcd(a.(*v1beta2.LocalEtcd), b.(*LocalEtcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.NodeRegistrationOptions)(nil), (*NodeRegistrationOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NodeRegistrationOptions_To_upstreamv1beta4_NodeRegistrationOptions(a.(*v1beta2.NodeRegistrationOptions), b.(*NodeRegistrationOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.ProxyConfiguration)(nil), (*Proxy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_Proxy(a.(*v1beta2.ProxyConfiguration), b.(*Proxy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.Scheduler)(nil), (*ControlPlaneComponent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Scheduler_To_upstreamv1beta4_ControlPlaneComponent(a.(*v1beta2.Scheduler), b.(*ControlPlaneComponent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.Timeouts)(nil), (*Timeouts)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Timeouts_To_upstreamv1beta4_Timeouts(a.(*v1beta2.Timeouts), b.(*Timeouts), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(in *APIEndpoint, out *v1beta2.APIEndpoint, s conversion.Scope) error {
	out.AdvertiseAddress = in.AdvertiseAddress
	out.BindPort = in.BindPort
	return nil
}

// Convert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint is an autogenerated conversion function.
func Convert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(in *APIEndpoint, out *v1beta2.APIEndpoint, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(in, out, s)
}

func autoConvert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(in *v1beta2.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.AdvertiseAddress = in.AdvertiseAddress
	out.BindPort = in.BindPort
	return nil
}

// Convert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint is an autogenerated conversion function.
func Convert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(in *v1beta2.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(in, out, s)
}

func autoConvert_upstreamv1beta4_APIServer_To_v1beta2_APIServer(in *APIServer, out *v1beta2.APIServer, s conversion.Scope) error {
	// WARNING: in.ControlPlaneComponent requires manual conversion: does not exist in peer-type
	out.CertSANs = *(*[]string)(unsafe.Pointer(&in.CertSANs))
	return nil
}

func autoConvert_v1beta2_APIServer_To_upstreamv1beta4_APIServer(in *v1beta2.APIServer, out *APIServer, s conversion.Scope) error {
	// WARNING: in.ExtraArgs requires manual conversion: does not exist in peer-type
	// WARNING: in.ExtraVolumes requires manual conversion: does not exist in peer-type
	// WARNING: in.ExtraEnvs requires manual conversion: does not exist in peer-type
	out.CertSANs = *(*[]string)(unsafe.Pointer(&in.CertSANs))
	return nil
}

func autoConvert_upstreamv1beta4_Arg_To_v1beta2_Arg(in *Arg, out *v1beta2.Arg, s conversion.Scope) error {
	out.Name = in.Name
	if err := v1.Convert_string_To_Pointer_string(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_upstreamv1beta4_Arg_To_v1beta2_Arg is an autogenerated conversion function.
func Convert_upstreamv1beta4_Arg_To_v1beta2_Arg(in *Arg, out *v1beta2.Arg, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_Arg_To_v1beta2_Arg(in, out, s)
}

func autoConvert_v1beta2_Arg_To_upstreamv1beta4_Arg(in *v1beta2.Arg, out *Arg, s conversion.Scope) error {
	out.Name = in.Name
	if err := v1.Convert_Pointer_string_To_string(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_Arg_To_upstreamv1beta4_Arg is an autogenerated conversion function.
func Convert_v1beta2_Arg_To_upstreamv1beta4_Arg(in *v1beta2.Arg, out *Arg, s conversion.Scope) error {
	return autoConvert_v1beta2_Arg_To_upstreamv1beta4_Arg(in, out, s)
}

func autoConvert_upstreamv1beta4_BootstrapToken_To_v1beta2_BootstrapToken(in *BootstrapToken, out *v1beta2.BootstrapToken, s conversion.Scope) error {
	// WARNING: in.Token requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.BootstrapTokenString vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.BootstrapTokenString)
	out.Description = in.Description
	// WARNING: in.TTL requires manual conversion: does not exist in peer-type
	// WARNING: in.Expires requires manual conversion: inconvertible types (*k8s.io/apimachinery/pkg/apis/meta/v1.Time vs k8s.io/apimachinery/pkg/apis/meta/v1.Time)
	out.Usages = *(*[]string)(unsafe.Pointer(&in.Usages))
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	return nil
}

func autoConvert_v1beta2_BootstrapToken_To_upstreamv1beta4_BootstrapToken(in *v1beta2.BootstrapToken, out *BootstrapToken, s conversion.Scope) error {
	// WARNING: in.Token requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.BootstrapTokenString vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.BootstrapTokenString)
	out.Description = in.Description
	// WARNING: in.TTLSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.Expires requires manual conversion: inconvertible types (k8s.io/apimachinery/pkg/apis/meta/v1.Time vs *k8s.io/apimachinery/pkg/apis/meta/v1.Time)
	out.Usages = *(*[]string)(unsafe.Pointer(&in.Usages))
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	return nil
}

func autoConvert_upstreamv1beta4_BootstrapTokenDiscovery_To_v1beta2_BootstrapTokenDiscovery(in *BootstrapTokenDiscovery, out *v1beta2.BootstrapTokenDiscovery, s conversion.Scope) error {
	out.Token = in.Token
	out.APIServerEndpoint = in.APIServerEndpoint
	out.CACertHashes = *(*[]string)(unsafe.Pointer(&in.CACertHashes))
	if err := v1.Convert_bool_To_Pointer_bool(&in.UnsafeSkipCAVerification, &out.UnsafeSkipCAVerification, s); err != nil {
		return err
	}
	return nil
}

// Convert_upstreamv1beta4_BootstrapTokenDiscovery_To_v1beta2_BootstrapTokenDiscovery is an autogenerated conversion function.
func Convert_upstreamv1beta4_BootstrapTokenDiscovery_To_v1beta2_BootstrapTokenDiscovery(in *BootstrapTokenDiscovery, out *v1beta2.BootstrapTokenDiscovery, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BootstrapTokenDiscovery_To_v1beta2_BootstrapTokenDiscovery(in, out, s)
}

func autoConvert_v1beta2_BootstrapTokenDiscovery_To_upstreamv1beta4_BootstrapTokenDiscovery(in *v1beta2.BootstrapTokenDiscovery, out *BootstrapTokenDiscovery, s conversion.Scope) error {
	out.Token = in.Token
	out.APIServerEndpoint = in.APIServerEndpoint
	out.CACertHashes = *(*[]string)(unsafe.Pointer(&in.CACertHashes))
	if err := v1.Convert_Pointer_bool_To_bool(&in.UnsafeSkipCAVerification, &out.UnsafeSkipCAVerification, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_BootstrapTokenDiscovery_To_upstreamv1beta4_BootstrapTokenDiscovery is an autogenerated conversion function.
func Convert_v1beta2_BootstrapTokenDiscovery_To_upstreamv1beta4_BootstrapTokenDiscovery(in *v1beta2.BootstrapTokenDiscovery, out *BootstrapTokenDiscovery, s conversion.Scope) error {
	return autoConvert_v1beta2_BootstrapTokenDiscovery_To_upstreamv1beta4_BootstrapTokenDiscovery(in, out, s)
}

func autoConvert_upstreamv1beta4_BootstrapTokenString_To_v1beta2_BootstrapTokenString(in *BootstrapTokenString, out *v1beta2.BootstrapTokenString, s conversion.Scope) error {
	out.ID = in.ID
	out.Secret = in.Secret
	return nil
}

// Convert_upstreamv1beta4_BootstrapTokenString_To_v1beta2_BootstrapTokenString is an autogenerated conversion function.
func Convert_upstreamv1beta4_BootstrapTokenString_To_v1beta2_BootstrapTokenString(in *BootstrapTokenString, out *v1beta2.BootstrapTokenString, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BootstrapTokenString_To_v1beta2_BootstrapTokenString(in, out, s)
}

func autoConvert_v1beta2_BootstrapTokenString_To_upstreamv1beta4_BootstrapTokenString(in *v1beta2.BootstrapTokenString, out *BootstrapTokenString, s conversion.Scope) error {
	out.ID = in.ID
	out.Secret = in.Secret
	return nil
}

// Convert_v1beta2_BootstrapTokenString_To_upstreamv1beta4_BootstrapTokenString is an autogenerated conversion function.
func Convert_v1beta2_BootstrapTokenString_To_upstreamv1beta4_BootstrapTokenString(in *v1beta2.BootstrapTokenString, out *BootstrapTokenString, s conversion.Scope) error {
	return autoConvert_v1beta2_BootstrapTokenString_To_upstreamv1beta4_BootstrapTokenString(in, out, s)
}

func autoConvert_upstreamv1beta4_BottlerocketAdmin_To_v1beta2_BottlerocketAdmin(in *BottlerocketAdmin, out *v1beta2.BottlerocketAdmin, s conversion.Scope) error {
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_BottlerocketAdmin_To_upstreamv1beta4_BottlerocketAdmin(in *v1beta2.BottlerocketAdmin, out *BottlerocketAdmin, s conversion.Scope) error {
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_upstreamv1beta4_BottlerocketBootSettings_To_v1beta2_BottlerocketBootSettings(in *BottlerocketBootSettings, out *v1beta2.BottlerocketBootSettings, s conversion.Scope) error {
	out.BootKernelParameters = *(*map[string][]string)(unsafe.Pointer(&in.BootKernelParameters))
	return nil
}

// Convert_upstreamv1beta4_BottlerocketBootSettings_To_v1beta2_BottlerocketBootSettings is an autogenerated conversion function.
func Convert_upstreamv1beta4_BottlerocketBootSettings_To_v1beta2_BottlerocketBootSettings(in *BottlerocketBootSettings, out *v1beta2.BottlerocketBootSettings, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BottlerocketBootSettings_To_v1beta2_BottlerocketBootSettings(in, out, s)
}

func autoConvert_v1beta2_BottlerocketBootSettings_To_upstreamv1beta4_BottlerocketBootSettings(in *v1beta2.BottlerocketBootSettings, out *BottlerocketBootSettings, s conversion.Scope) error {
	out.BootKernelParameters = *(*map[string][]string)(unsafe.Pointer(&in.BootKernelParameters))
	return nil
}

// Convert_v1beta2_BottlerocketBootSettings_To_upstreamv1beta4_BottlerocketBootSettings is an autogenerated conversion function.
func Convert_v1beta2_BottlerocketBootSettings_To_upstreamv1beta4_BottlerocketBootSettings(in *v1beta2.BottlerocketBootSettings, out *BottlerocketBootSettings, s conversion.Scope) error {
	return autoConvert_v1beta2_BottlerocketBootSettings_To_upstreamv1beta4_BottlerocketBootSettings(in, out, s)
}

func autoConvert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(in *BottlerocketBootstrap, out *v1beta2.BottlerocketBootstrap, s conversion.Scope) error {
	out.ImageRepository = in.ImageRepository
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap is an autogenerated conversion function.
func Convert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(in *BottlerocketBootstrap, out *v1beta2.BottlerocketBootstrap, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(in, out, s)
}

func autoConvert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(in *v1beta2.BottlerocketBootstrap, out *BottlerocketBootstrap, s conversion.Scope) error {
	out.ImageRepository = in.ImageRepository
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap is an autogenerated conversion function.
func Convert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(in *v1beta2.BottlerocketBootstrap, out *BottlerocketBootstrap, s conversion.Scope) error {
	return autoConvert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(in, out, s)
}

func autoConvert_upstreamv1beta4_BottlerocketBootstrapContainer_To_v1beta2_BottlerocketBootstrapContainer(in *BottlerocketBootstrapContainer, out *v1beta2.BottlerocketBootstrapContainer, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	out.Essential = in.Essential
	out.Mode = in.Mode
	out.UserData = in.UserData
	return nil
}

func autoConvert_v1beta2_BottlerocketBootstrapContainer_To_upstreamv1beta4_BottlerocketBootstrapContainer(in *v1beta2.BottlerocketBootstrapContainer, out *BottlerocketBootstrapContainer, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	out.Essential = in.Essential
	out.Mode = in.Mode
	out.UserData = in.UserData
	return nil
}

func autoConvert_upstreamv1beta4_BottlerocketControl_To_v1beta2_BottlerocketControl(in *BottlerocketControl, out *v1beta2.BottlerocketControl, s conversion.Scope) error {
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_BottlerocketControl_To_upstreamv1beta4_BottlerocketControl(in *v1beta2.BottlerocketControl, out *BottlerocketControl, s conversion.Scope) error {
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_upstreamv1beta4_BottlerocketHostContainer_To_v1beta2_BottlerocketHostContainer(in *BottlerocketHostContainer, out *v1beta2.BottlerocketHostContainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Superpowered = in.Superpowered
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	out.UserData = in.UserData
	return nil
}

func autoConvert_v1beta2_BottlerocketHostContainer_To_upstreamv1beta4_BottlerocketHostContainer(in *v1beta2.BottlerocketHostContainer, out *BottlerocketHostContainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Superpowered = in.Superpowered
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	out.UserData = in.UserData
	return nil
}

func autoConvert_upstreamv1beta4_BottlerocketKernelSettings_To_v1beta2_BottlerocketKernelSettings(in *BottlerocketKernelSettings, out *v1beta2.BottlerocketKernelSettings, s conversion.Scope) error {
	out.SysctlSettings = *(*map[string]string)(unsafe.Pointer(&in.SysctlSettings))
	return nil
}

// Convert_upstreamv1beta4_BottlerocketKernelSettings_To_v1beta2_BottlerocketKernelSettings is an autogenerated conversion function.
func Convert_upstreamv1beta4_BottlerocketKernelSettings_To_v1beta2_BottlerocketKernelSettings(in *BottlerocketKernelSettings, out *v1beta2.BottlerocketKernelSettings, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BottlerocketKernelSettings_To_v1beta2_BottlerocketKernelSettings(in, out, s)
}

func autoConvert_v1beta2_BottlerocketKernelSettings_To_upstreamv1beta4_BottlerocketKernelSettings(in *v1beta2.BottlerocketKernelSettings, out *BottlerocketKernelSettings, s conversion.Scope) error {
	out.SysctlSettings = *(*map[string]string)(unsafe.Pointer(&in.SysctlSettings))
	return nil
}

// Convert_v1beta2_BottlerocketKernelSettings_To_upstreamv1beta4_BottlerocketKernelSettings is an autogenerated conversion function.
func Convert_v1beta2_BottlerocketKernelSettings_To_upstreamv1beta4_BottlerocketKernelSettings(in *v1beta2.BottlerocketKernelSettings, out *BottlerocketKernelSettings, s conversion.Scope) error {
	return autoConvert_v1beta2_BottlerocketKernelSettings_To_upstreamv1beta4_BottlerocketKernelSettings(in, out, s)
}

func autoConvert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings(in *BottlerocketKubernetesSettings, out *v1beta2.BottlerocketKubernetesSettings, s conversion.Scope) error {
	out.MaxPods = in.MaxPods
	out.AllowedUnsafeSysctls = *(*[]string)(unsafe.Pointer(&in.AllowedUnsafeSysctls))
	out.ClusterDNSIPs = *(*[]string)(unsafe.Pointer(&in.ClusterDNSIPs))
	return nil
}

// Convert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings is an autogenerated conversion function.
func Convert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings(in *BottlerocketKubernetesSettings, out *v1beta2.BottlerocketKubernetesSettings, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings(in, out, s)
}

func autoConvert_v1beta2_BottlerocketKubernetesSettings_To_upstreamv1beta4_BottlerocketKubernetesSettings(in *v1beta2.BottlerocketKubernetesSettings, out *BottlerocketKubernetesSettings, s conversion.Scope) error {
	out.AllowedUnsafeSysctls = *(*[]string)(unsafe.Pointer(&in.AllowedUnsafeSysctls))
	out.ClusterDNSIPs = *(*[]string)(unsafe.Pointer(&in.ClusterDNSIPs))
	// WARNING: in.ClusterDomain requires manual conversion: does not exist in peer-type
	// WARNING: in.ContainerLogMaxFiles requires manual conversion: does not exist in peer-type
	// WARNING: in.ContainerLogMaxSize requires manual conversion: does not exist in peer-type
	// WARNING: in.CPUCFSQuota requires manual conversion: does not exist in peer-type
	// WARNING: in.CPUManagerPolicy requires manual conversion: does not exist in peer-type
	// WARNING: in.CPUManagerPolicyOptions requires manual conversion: does not exist in peer-type
	// WARNING: in.CPUManagerReconcilePeriod requires manual conversion: does not exist in peer-type
	// WARNING: in.EventBurst requires manual conversion: does not exist in peer-type
	// WARNING: in.EventRecordQPS requires manual conversion: does not exist in peer-type
	// WARNING: in.EvictionHard requires manual conversion: does not exist in peer-type
	// WARNING: in.EvictionMaxPodGracePeriod requires manual conversion: does not exist in peer-type
	// WARNING: in.EvictionSoft requires manual conversion: does not exist in peer-type
	// WARNING: in.EvictionSoftGracePeriod requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageGCHighThresholdPercent requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageGCLowThresholdPercent requires manual conversion: does not exist in peer-type
	// WARNING: in.KubeAPIBurst requires manual conversion: does not exist in peer-type
	// WARNING: in.KubeAPIQPS requires manual conversion: does not exist in peer-type
	// WARNING: in.KubeReserved requires manual conversion: does not exist in peer-type
	out.MaxPods = in.MaxPods
	// WARNING: in.MemoryManagerPolicy requires manual conversion: does not exist in peer-type
	// WARNING: in.PodPidsLimit requires manual conversion: does not exist in peer-type
	// WARNING: in.ProviderID requires manual conversion: does not exist in peer-type
	// WARNING: in.RegistryBurst requires manual conversion: does not exist in peer-type
	// WARNING: in.RegistryPullQPS requires manual conversion: does not exist in peer-type
	// WARNING: in.ShutdownGracePeriod requires manual conversion: does not exist in peer-type
	// WARNING: in.ShutdownGracePeriodCriticalPods requires manual conversion: does not exist in peer-type
	// WARNING: in.SystemReserved requires manual conversion: does not exist in peer-type
	// WARNING: in.TopologyManagerPolicy requires manual conversion: does not exist in peer-type
	// WARNING: in.TopologyManagerScope requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(in *BottlerocketSettings, out *v1beta2.BottlerocketSettings, s conversion.Scope) error {
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(v1beta2.BottlerocketKubernetesSettings)
		if err := Convert_upstreamv1beta4_BottlerocketKubernetesSettings_To_v1beta2_BottlerocketKubernetesSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Kubernetes = nil
	}
	out.Kernel = (*v1beta2.BottlerocketKernelSettings)(unsafe.Pointer(in.Kernel))
	out.Boot = (*v1beta2.BottlerocketBootSettings)(unsafe.Pointer(in.Boot))
	return nil
}

// Convert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings is an autogenerated conversion function.
func Convert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(in *BottlerocketSettings, out *v1beta2.BottlerocketSettings, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(in, out, s)
}

func autoConvert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(in *v1beta2.BottlerocketSettings, out *BottlerocketSettings, s conversion.Scope) error {
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(BottlerocketKubernetesSettings)
		if err := Convert_v1beta2_BottlerocketKubernetesSettings_To_upstreamv1beta4_BottlerocketKubernetesSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Kubernetes = nil
	}
	out.Kernel = (*BottlerocketKernelSettings)(unsafe.Pointer(in.Kernel))
	out.Boot = (*BottlerocketBootSettings)(unsafe.Pointer(in.Boot))
	return nil
}

// Convert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings is an autogenerated conversion function.
func Convert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(in *v1beta2.BottlerocketSettings, out *BottlerocketSettings, s conversion.Scope) error {
	return autoConvert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(in, out, s)
}

func autoConvert_upstreamv1beta4_CertBundle_To_v1beta2_CertBundle(in *CertBundle, out *v1beta2.CertBundle, s conversion.Scope) error {
	out.Name = in.Name
	out.Data = in.Data
	return nil
}

// Convert_upstreamv1beta4_CertBundle_To_v1beta2_CertBundle is an autogenerated conversion function.
func Convert_upstreamv1beta4_CertBundle_To_v1beta2_CertBundle(in *CertBundle, out *v1beta2.CertBundle, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_CertBundle_To_v1beta2_CertBundle(in, out, s)
}

func autoConvert_v1beta2_CertBundle_To_upstreamv1beta4_CertBundle(in *v1beta2.CertBundle, out *CertBundle, s conversion.Scope) error {
	out.Name = in.Name
	out.Data = in.Data
	return nil
}

// Convert_v1beta2_CertBundle_To_upstreamv1beta4_CertBundle is an autogenerated conversion function.
func Convert_v1beta2_CertBundle_To_upstreamv1beta4_CertBundle(in *v1beta2.CertBundle, out *CertBundle, s conversion.Scope) error {
	return autoConvert_v1beta2_CertBundle_To_upstreamv1beta4_CertBundle(in, out, s)
}

func autoConvert_upstreamv1beta4_ClusterConfiguration_To_v1beta2_ClusterConfiguration(in *ClusterConfiguration, out *v1beta2.ClusterConfiguration, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	if err := Convert_upstreamv1beta4_Pause_To_v1beta2_Pause(&in.Pause, &out.Pause, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(&in.BottlerocketBootstrap, &out.BottlerocketBootstrap, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_BottlerocketAdmin_To_v1beta2_BottlerocketAdmin(&in.BottlerocketAdmin, &out.BottlerocketAdmin, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_BottlerocketControl_To_v1beta2_BottlerocketControl(&in.BottlerocketControl, &out.BottlerocketControl, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_Proxy_To_v1beta2_ProxyConfiguration(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(&in.RegistryMirror, &out.RegistryMirror, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_Etcd_To_v1beta2_Etcd(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	if in.BottlerocketHostContainers != nil {
		in, out := &in.BottlerocketHostContainers, &out.BottlerocketHostContainers
		*out = make([]v1beta2.BottlerocketHostContainer, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_BottlerocketHostContainer_To_v1beta2_BottlerocketHostContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketHostContainers = nil
	}
	if in.BottlerocketCustomBootstrapContainers != nil {
		in, out := &in.BottlerocketCustomBootstrapContainers, &out.BottlerocketCustomBootstrapContainers
		*out = make([]v1beta2.BottlerocketBootstrapContainer, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_BottlerocketBootstrapContainer_To_v1beta2_BottlerocketBootstrapContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomBootstrapContainers = nil
	}
	if in.Bottlerocket != nil {
		in, out := &in.Bottlerocket, &out.Bottlerocket
		*out = new(v1beta2.BottlerocketSettings)
		if err := Convert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Bottlerocket = nil
	}
	out.CertBundles = *(*[]v1beta2.CertBundle)(unsafe.Pointer(&in.CertBundles))
	// WARNING: in.Networking requires manual conversion: does not exist in peer-type
	// WARNING: in.KubernetesVersion requires manual conversion: does not exist in peer-type
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if err := Convert_upstreamv1beta4_APIServer_To_v1beta2_APIServer(&in.APIServer, &out.APIServer, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_ControlPlaneComponent_To_v1beta2_ControllerManager(&in.ControllerManager, &out.ControllerManager, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_ControlPlaneComponent_To_v1beta2_Scheduler(&in.Scheduler, &out.Scheduler, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_DNS_To_v1beta2_DNS(&in.DNS, &out.DNS, s); err != nil {
		return err
	}
	out.CertificatesDir = in.CertificatesDir
	out.ImageRepository = in.ImageRepository
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	// WARNING: in.ClusterName requires manual conversion: does not exist in peer-type
	out.EncryptionAlgorithm = v1beta2.EncryptionAlgorithmType(in.EncryptionAlgorithm)
	// WARNING: in.CertificateValidityPeriod requires manual conversion: does not exist in peer-type
	// WARNING: in.CACertificateValidityPeriod requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_ClusterConfiguration_To_upstreamv1beta4_ClusterConfiguration(in *v1beta2.ClusterConfiguration, out *ClusterConfiguration, s conversion.Scope) error {
	if err := Convert_v1beta2_Pause_To_upstreamv1beta4_Pause(&in.Pause, &out.Pause, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(&in.BottlerocketBootstrap, &out.BottlerocketBootstrap, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketAdmin_To_upstreamv1beta4_BottlerocketAdmin(&in.BottlerocketAdmin, &out.BottlerocketAdmin, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketControl_To_upstreamv1beta4_BottlerocketControl(&in.BottlerocketControl, &out.BottlerocketControl, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_Proxy(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(&in.RegistryMirror, &out.RegistryMirror, s); err != nil {
		return err
	}
	if in.BottlerocketHostContainers != nil {
		in, out := &in.BottlerocketHostContainers, &out.BottlerocketHostContainers
		*out = make([]BottlerocketHostContainer, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_BottlerocketHostContainer_To_upstreamv1beta4_BottlerocketHostContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketHostContainers = nil
	}
	if in.BottlerocketCustomBootstrapContainers != nil {
		in, out := &in.BottlerocketCustomBootstrapContainers, &out.BottlerocketCustomBootstrapContainers
		*out = make([]BottlerocketBootstrapContainer, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_BottlerocketBootstrapContainer_To_upstreamv1beta4_BottlerocketBootstrapContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomBootstrapContainers = nil
	}
	if in.Bottlerocket != nil {
		in, out := &in.Bottlerocket, &out.Bottlerocket
		*out = new(BottlerocketSettings)
		if err := Convert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Bottlerocket = nil
	}
	out.CertBundles = *(*[]CertBundle)(unsafe.Pointer(&in.CertBundles))
	if err := Convert_v1beta2_Etcd_To_upstreamv1beta4_Etcd(&in.Etcd, &out.Etcd, s); err != nil {
		return err
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if err := Convert_v1beta2_APIServer_To_upstreamv1beta4_APIServer(&in.APIServer, &out.APIServer, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_ControllerManager_To_upstreamv1beta4_ControlPlaneComponent(&in.ControllerManager, &out.ControllerManager, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_Scheduler_To_upstreamv1beta4_ControlPlaneComponent(&in.Scheduler, &out.Scheduler, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_DNS_To_upstreamv1beta4_DNS(&in.DNS, &out.DNS, s); err != nil {
		return err
	}
	out.CertificatesDir = in.CertificatesDir
	out.ImageRepository = in.ImageRepository
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	// WARNING: in.CertificateValidityPeriodDays requires manual conversion: does not exist in peer-type
	// WARNING: in.CACertificateValidityPeriodDays requires manual conversion: does not exist in peer-type
	out.EncryptionAlgorithm = EncryptionAlgorithmType(in.EncryptionAlgorithm)
	return nil
}

func autoConvert_upstreamv1beta4_DNS_To_v1beta2_DNS(in *DNS, out *v1beta2.DNS, s conversion.Scope) error {
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	// WARNING: in.Disabled requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_DNS_To_upstreamv1beta4_DNS(in *v1beta2.DNS, out *DNS, s conversion.Scope) error {
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_upstreamv1beta4_Discovery_To_v1beta2_Discovery(in *Discovery, out *v1beta2.Discovery, s conversion.Scope) error {
	// WARNING: in.BootstrapToken requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.BootstrapTokenDiscovery vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.BootstrapTokenDiscovery)
	// WARNING: in.File requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.FileDiscovery vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.FileDiscovery)
	out.TLSBootstrapToken = in.TLSBootstrapToken
	return nil
}

func autoConvert_v1beta2_Discovery_To_upstreamv1beta4_Discovery(in *v1beta2.Discovery, out *Discovery, s conversion.Scope) error {
	// WARNING: in.BootstrapToken requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.BootstrapTokenDiscovery vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.BootstrapTokenDiscovery)
	// WARNING: in.File requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.FileDiscovery vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.FileDiscovery)
	out.TLSBootstrapToken = in.TLSBootstrapToken
	return nil
}

func autoConvert_upstreamv1beta4_EnvVar_To_v1beta2_EnvVar(in *EnvVar, out *v1beta2.EnvVar, s conversion.Scope) error {
	out.EnvVar = in.EnvVar
	return nil
}

// Convert_upstreamv1beta4_EnvVar_To_v1beta2_EnvVar is an autogenerated conversion function.
func Convert_upstreamv1beta4_EnvVar_To_v1beta2_EnvVar(in *EnvVar, out *v1beta2.EnvVar, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_EnvVar_To_v1beta2_EnvVar(in, out, s)
}

func autoConvert_v1beta2_EnvVar_To_upstreamv1beta4_EnvVar(in *v1beta2.EnvVar, out *EnvVar, s conversion.Scope) error {
	out.EnvVar = in.EnvVar
	return nil
}

// Convert_v1beta2_EnvVar_To_upstreamv1beta4_EnvVar is an autogenerated conversion function.
func Convert_v1beta2_EnvVar_To_upstreamv1beta4_EnvVar(in *v1beta2.EnvVar, out *EnvVar, s conversion.Scope) error {
	return autoConvert_v1beta2_EnvVar_To_upstreamv1beta4_EnvVar(in, out, s)
}

func autoConvert_upstreamv1beta4_Etcd_To_v1beta2_Etcd(in *Etcd, out *v1beta2.Etcd, s conversion.Scope) error {
	// WARNING: in.Local requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.LocalEtcd vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.LocalEtcd)
	// WARNING: in.External requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.ExternalEtcd vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.ExternalEtcd)
	return nil
}

func autoConvert_v1beta2_Etcd_To_upstreamv1beta4_Etcd(in *v1beta2.Etcd, out *Etcd, s conversion.Scope) error {
	// WARNING: in.Local requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.LocalEtcd vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.LocalEtcd)
	// WARNING: in.External requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.ExternalEtcd vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.ExternalEtcd)
	return nil
}

func autoConvert_upstreamv1beta4_ExternalEtcd_To_v1beta2_ExternalEtcd(in *ExternalEtcd, out *v1beta2.ExternalEtcd, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_upstreamv1beta4_ExternalEtcd_To_v1beta2_ExternalEtcd is an autogenerated conversion function.
func Convert_upstreamv1beta4_ExternalEtcd_To_v1beta2_ExternalEtcd(in *ExternalEtcd, out *v1beta2.ExternalEtcd, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_ExternalEtcd_To_v1beta2_ExternalEtcd(in, out, s)
}

func autoConvert_v1beta2_ExternalEtcd_To_upstreamv1beta4_ExternalEtcd(in *v1beta2.ExternalEtcd, out *ExternalEtcd, s conversion.Scope) error {
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_v1beta2_ExternalEtcd_To_upstreamv1beta4_ExternalEtcd is an autogenerated conversion function.
func Convert_v1beta2_ExternalEtcd_To_upstreamv1beta4_ExternalEtcd(in *v1beta2.ExternalEtcd, out *ExternalEtcd, s conversion.Scope) error {
	return autoConvert_v1beta2_ExternalEtcd_To_upstreamv1beta4_ExternalEtcd(in, out, s)
}

func autoConvert_upstreamv1beta4_FileDiscovery_To_v1beta2_FileDiscovery(in *FileDiscovery, out *v1beta2.FileDiscovery, s conversion.Scope) error {
	out.KubeConfigPath = in.KubeConfigPath
	return nil
}

// Convert_upstreamv1beta4_FileDiscovery_To_v1beta2_FileDiscovery is an autogenerated conversion function.
func Convert_upstreamv1beta4_FileDiscovery_To_v1beta2_FileDiscovery(in *FileDiscovery, out *v1beta2.FileDiscovery, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_FileDiscovery_To_v1beta2_FileDiscovery(in, out, s)
}

func autoConvert_v1beta2_FileDiscovery_To_upstreamv1beta4_FileDiscovery(in *v1beta2.FileDiscovery, out *FileDiscovery, s conversion.Scope) error {
	out.KubeConfigPath = in.KubeConfigPath
	// WARNING: in.KubeConfig requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_upstreamv1beta4_HostPathMount_To_v1beta2_HostPathMount(in *HostPathMount, out *v1beta2.HostPathMount, s conversion.Scope) error {
	out.Name = in.Name
	out.HostPath = in.HostPath
	out.MountPath = in.MountPath
	if err := v1.Convert_bool_To_Pointer_bool(&in.ReadOnly, &out.ReadOnly, s); err != nil {
		return err
	}
	out.PathType = corev1.HostPathType(in.PathType)
	return nil
}

// Convert_upstreamv1beta4_HostPathMount_To_v1beta2_HostPathMount is an autogenerated conversion function.
func Convert_upstreamv1beta4_HostPathMount_To_v1beta2_HostPathMount(in *HostPathMount, out *v1beta2.HostPathMount, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_HostPathMount_To_v1beta2_HostPathMount(in, out, s)
}

func autoConvert_v1beta2_HostPathMount_To_upstreamv1beta4_HostPathMount(in *v1beta2.HostPathMount, out *HostPathMount, s conversion.Scope) error {
	out.Name = in.Name
	out.HostPath = in.HostPath
	out.MountPath = in.MountPath
	if err := v1.Convert_Pointer_bool_To_bool(&in.ReadOnly, &out.ReadOnly, s); err != nil {
		return err
	}
	out.PathType = corev1.HostPathType(in.PathType)
	return nil
}

// Convert_v1beta2_HostPathMount_To_upstreamv1beta4_HostPathMount is an autogenerated conversion function.
func Convert_v1beta2_HostPathMount_To_upstreamv1beta4_HostPathMount(in *v1beta2.HostPathMount, out *HostPathMount, s conversion.Scope) error {
	return autoConvert_v1beta2_HostPathMount_To_upstreamv1beta4_HostPathMount(in, out, s)
}

func autoConvert_upstreamv1beta4_InitConfiguration_To_v1beta2_InitConfiguration(in *InitConfiguration, out *v1beta2.InitConfiguration, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	// WARNING: in.Pause requires manual conversion: does not exist in peer-type
	// WARNING: in.BottlerocketBootstrap requires manual conversion: does not exist in peer-type
	// WARNING: in.Proxy requires manual conversion: does not exist in peer-type
	if in.BootstrapTokens != nil {
		in, out := &in.BootstrapTokens, &out.BootstrapTokens
		*out = make([]v1beta2.BootstrapToken, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_BootstrapToken_To_v1beta2_BootstrapToken(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BootstrapTokens = nil
	}
	// WARNING: in.DryRun requires manual conversion: does not exist in peer-type
	if err := Convert_upstreamv1beta4_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOptions(&in.NodeRegistration, &out.NodeRegistration, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(&in.LocalAPIEndpoint, &out.LocalAPIEndpoint, s); err != nil {
		return err
	}
	// WARNING: in.CertificateKey requires manual conversion: does not exist in peer-type
	out.SkipPhases = *(*[]string)(unsafe.Pointer(&in.SkipPhases))
	// WARNING: in.Patches requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Patches vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Patches)
	// WARNING: in.Timeouts requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Timeouts vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Timeouts)
	return nil
}

func autoConvert_v1beta2_InitConfiguration_To_upstreamv1beta4_InitConfiguration(in *v1beta2.InitConfiguration, out *InitConfiguration, s conversion.Scope) error {
	if in.BootstrapTokens != nil {
		in, out := &in.BootstrapTokens, &out.BootstrapTokens
		*out = make([]BootstrapToken, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_BootstrapToken_To_upstreamv1beta4_BootstrapToken(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BootstrapTokens = nil
	}
	if err := Convert_v1beta2_NodeRegistrationOptions_To_upstreamv1beta4_NodeRegistrationOptions(&in.NodeRegistration, &out.NodeRegistration, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(&in.LocalAPIEndpoint, &out.LocalAPIEndpoint, s); err != nil {
		return err
	}
	out.SkipPhases = *(*[]string)(unsafe.Pointer(&in.SkipPhases))
	// WARNING: in.Patches requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Patches vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Patches)
	// WARNING: in.Timeouts requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Timeouts vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Timeouts)
	return nil
}

func autoConvert_upstreamv1beta4_JoinConfiguration_To_v1beta2_JoinConfiguration(in *JoinConfiguration, out *v1beta2.JoinConfiguration, s conversion.Scope) error {
	// WARNING: in.TypeMeta requires manual conversion: does not exist in peer-type
	if err := Convert_upstreamv1beta4_BottlerocketAdmin_To_v1beta2_BottlerocketAdmin(&in.BottlerocketAdmin, &out.BottlerocketAdmin, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_BottlerocketControl_To_v1beta2_BottlerocketControl(&in.BottlerocketControl, &out.BottlerocketControl, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(&in.RegistryMirror, &out.RegistryMirror, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_Pause_To_v1beta2_Pause(&in.Pause, &out.Pause, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_BottlerocketBootstrap_To_v1beta2_BottlerocketBootstrap(&in.BottlerocketBootstrap, &out.BottlerocketBootstrap, s); err != nil {
		return err
	}
	if err := Convert_upstreamv1beta4_Proxy_To_v1beta2_ProxyConfiguration(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	// WARNING: in.DryRun requires manual conversion: does not exist in peer-type
	if err := Convert_upstreamv1beta4_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOptions(&in.NodeRegistration, &out.NodeRegistration, s); err != nil {
		return err
	}
	out.CACertPath = in.CACertPath
	if err := Convert_upstreamv1beta4_Discovery_To_v1beta2_Discovery(&in.Discovery, &out.Discovery, s); err != nil {
		return err
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(v1beta2.JoinControlPlane)
		if err := Convert_upstreamv1beta4_JoinControlPlane_To_v1beta2_JoinControlPlane(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.ControlPlane = nil
	}
	if in.BottlerocketCustomHostContainers != nil {
		in, out := &in.BottlerocketCustomHostContainers, &out.BottlerocketCustomHostContainers
		*out = make([]v1beta2.BottlerocketHostContainer, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_BottlerocketHostContainer_To_v1beta2_BottlerocketHostContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomHostContainers = nil
	}
	if in.BottlerocketCustomBootstrapContainers != nil {
		in, out := &in.BottlerocketCustomBootstrapContainers, &out.BottlerocketCustomBootstrapContainers
		*out = make([]v1beta2.BottlerocketBootstrapContainer, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_BottlerocketBootstrapContainer_To_v1beta2_BottlerocketBootstrapContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomBootstrapContainers = nil
	}
	if in.Bottlerocket != nil {
		in, out := &in.Bottlerocket, &out.Bottlerocket
		*out = new(v1beta2.BottlerocketSettings)
		if err := Convert_upstreamv1beta4_BottlerocketSettings_To_v1beta2_BottlerocketSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Bottlerocket = nil
	}
	out.CertBundles = *(*[]v1beta2.CertBundle)(unsafe.Pointer(&in.CertBundles))
	out.SkipPhases = *(*[]string)(unsafe.Pointer(&in.SkipPhases))
	// WARNING: in.Patches requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Patches vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Patches)
	// WARNING: in.Timeouts requires manual conversion: inconvertible types (*sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Timeouts vs sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Timeouts)
	return nil
}

func autoConvert_v1beta2_JoinConfiguration_To_upstreamv1beta4_JoinConfiguration(in *v1beta2.JoinConfiguration, out *JoinConfiguration, s conversion.Scope) error {
	if err := Convert_v1beta2_Pause_To_upstreamv1beta4_Pause(&in.Pause, &out.Pause, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketBootstrap_To_upstreamv1beta4_BottlerocketBootstrap(&in.BottlerocketBootstrap, &out.BottlerocketBootstrap, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketAdmin_To_upstreamv1beta4_BottlerocketAdmin(&in.BottlerocketAdmin, &out.BottlerocketAdmin, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_BottlerocketControl_To_upstreamv1beta4_BottlerocketControl(&in.BottlerocketControl, &out.BottlerocketControl, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_Proxy(&in.Proxy, &out.Proxy, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(&in.RegistryMirror, &out.RegistryMirror, s); err != nil {
		return err
	}
	if in.BottlerocketCustomHostContainers != nil {
		in, out := &in.BottlerocketCustomHostContainers, &out.BottlerocketCustomHostContainers
		*out = make([]BottlerocketHostContainer, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_BottlerocketHostContainer_To_upstreamv1beta4_BottlerocketHostContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomHostContainers = nil
	}
	if in.BottlerocketCustomBootstrapContainers != nil {
		in, out := &in.BottlerocketCustomBootstrapContainers, &out.BottlerocketCustomBootstrapContainers
		*out = make([]BottlerocketBootstrapContainer, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_BottlerocketBootstrapContainer_To_upstreamv1beta4_BottlerocketBootstrapContainer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.BottlerocketCustomBootstrapContainers = nil
	}
	if in.Bottlerocket != nil {
		in, out := &in.Bottlerocket, &out.Bottlerocket
		*out = new(BottlerocketSettings)
		if err := Convert_v1beta2_BottlerocketSettings_To_upstreamv1beta4_BottlerocketSettings(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Bottlerocket = nil
	}
	out.CertBundles = *(*[]CertBundle)(unsafe.Pointer(&in.CertBundles))
	if err := Convert_v1beta2_NodeRegistrationOptions_To_upstreamv1beta4_NodeRegistrationOptions(&in.NodeRegistration, &out.NodeRegistration, s); err != nil {
		return err
	}
	out.CACertPath = in.CACertPath
	if err := Convert_v1beta2_Discovery_To_upstreamv1beta4_Discovery(&in.Discovery, &out.Discovery, s); err != nil {
		return err
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(JoinControlPlane)
		if err := Convert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.ControlPlane = nil
	}
	out.SkipPhases = *(*[]string)(unsafe.Pointer(&in.SkipPhases))
	// WARNING: in.Patches requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Patches vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Patches)
	// WARNING: in.Timeouts requires manual conversion: inconvertible types (sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.Timeouts vs *sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.Timeouts)
	return nil
}

func autoConvert_upstreamv1beta4_JoinControlPlane_To_v1beta2_JoinControlPlane(in *JoinControlPlane, out *v1beta2.JoinControlPlane, s conversion.Scope) error {
	if err := Convert_upstreamv1beta4_APIEndpoint_To_v1beta2_APIEndpoint(&in.LocalAPIEndpoint, &out.LocalAPIEndpoint, s); err != nil {
		return err
	}
	// WARNING: in.CertificateKey requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane(in *v1beta2.JoinControlPlane, out *JoinControlPlane, s conversion.Scope) error {
	if err := Convert_v1beta2_APIEndpoint_To_upstreamv1beta4_APIEndpoint(&in.LocalAPIEndpoint, &out.LocalAPIEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane is an autogenerated conversion function.
func Convert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane(in *v1beta2.JoinControlPlane, out *JoinControlPlane, s conversion.Scope) error {
	return autoConvert_v1beta2_JoinControlPlane_To_upstreamv1beta4_JoinControlPlane(in, out, s)
}

func autoConvert_upstreamv1beta4_LocalEtcd_To_v1beta2_LocalEtcd(in *LocalEtcd, out *v1beta2.LocalEtcd, s conversion.Scope) error {
	// WARNING: in.ImageMeta requires manual conversion: does not exist in peer-type
	out.DataDir = in.DataDir
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]v1beta2.Arg, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_Arg_To_v1beta2_Arg(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.ExtraArgs = nil
	}
	// WARNING: in.ExtraEnvs requires manual conversion: inconvertible types ([]sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.EnvVar vs *[]sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.EnvVar)
	out.ServerCertSANs = *(*[]string)(unsafe.Pointer(&in.ServerCertSANs))
	out.PeerCertSANs = *(*[]string)(unsafe.Pointer(&in.PeerCertSANs))
	return nil
}

func autoConvert_v1beta2_LocalEtcd_To_upstreamv1beta4_LocalEtcd(in *v1beta2.LocalEtcd, out *LocalEtcd, s conversion.Scope) error {
	// WARNING: in.ImageRepository requires manual conversion: does not exist in peer-type
	// WARNING: in.ImageTag requires manual conversion: does not exist in peer-type
	out.DataDir = in.DataDir
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]Arg, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_Arg_To_upstreamv1beta4_Arg(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.ExtraArgs = nil
	}
	// WARNING: in.ExtraEnvs requires manual conversion: inconvertible types (*[]sigs.k8s.io/cluster-api/api/bootstrap/kubeadm/v1beta2.EnvVar vs []sigs.k8s.io/cluster-api/bootstrap/kubeadm/types/upstreamv1beta4.EnvVar)
	out.ServerCertSANs = *(*[]string)(unsafe.Pointer(&in.ServerCertSANs))
	out.PeerCertSANs = *(*[]string)(unsafe.Pointer(&in.PeerCertSANs))
	return nil
}

func autoConvert_upstreamv1beta4_Mirror_To_v1beta2_Mirror(in *Mirror, out *v1beta2.Mirror, s conversion.Scope) error {
	out.Registry = in.Registry
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	return nil
}

// Convert_upstreamv1beta4_Mirror_To_v1beta2_Mirror is an autogenerated conversion function.
func Convert_upstreamv1beta4_Mirror_To_v1beta2_Mirror(in *Mirror, out *v1beta2.Mirror, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_Mirror_To_v1beta2_Mirror(in, out, s)
}

func autoConvert_v1beta2_Mirror_To_upstreamv1beta4_Mirror(in *v1beta2.Mirror, out *Mirror, s conversion.Scope) error {
	out.Registry = in.Registry
	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
	return nil
}

// Convert_v1beta2_Mirror_To_upstreamv1beta4_Mirror is an autogenerated conversion function.
func Convert_v1beta2_Mirror_To_upstreamv1beta4_Mirror(in *v1beta2.Mirror, out *Mirror, s conversion.Scope) error {
	return autoConvert_v1beta2_Mirror_To_upstreamv1beta4_Mirror(in, out, s)
}

func autoConvert_upstreamv1beta4_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOptions(in *NodeRegistrationOptions, out *v1beta2.NodeRegistrationOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.CRISocket = in.CRISocket
	// WARNING: in.Taints requires manual conversion: inconvertible types ([]k8s.io/api/core/v1.Taint vs *[]k8s.io/api/core/v1.Taint)
	if in.KubeletExtraArgs != nil {
		in, out := &in.KubeletExtraArgs, &out.KubeletExtraArgs
		*out = make([]v1beta2.Arg, len(*in))
		for i := range *in {
			if err := Convert_upstreamv1beta4_Arg_To_v1beta2_Arg(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.KubeletExtraArgs = nil
	}
	out.IgnorePreflightErrors = *(*[]string)(unsafe.Pointer(&in.IgnorePreflightErrors))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.ImagePullSerial = (*bool)(unsafe.Pointer(in.ImagePullSerial))
	return nil
}

func autoConvert_v1beta2_NodeRegistrationOptions_To_upstreamv1beta4_NodeRegistrationOptions(in *v1beta2.NodeRegistrationOptions, out *NodeRegistrationOptions, s conversion.Scope) error {
	out.Name = in.Name
	out.CRISocket = in.CRISocket
	// WARNING: in.Taints requires manual conversion: inconvertible types (*[]k8s.io/api/core/v1.Taint vs []k8s.io/api/core/v1.Taint)
	if in.KubeletExtraArgs != nil {
		in, out := &in.KubeletExtraArgs, &out.KubeletExtraArgs
		*out = make([]Arg, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_Arg_To_upstreamv1beta4_Arg(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.KubeletExtraArgs = nil
	}
	out.IgnorePreflightErrors = *(*[]string)(unsafe.Pointer(&in.IgnorePreflightErrors))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.ImagePullSerial = (*bool)(unsafe.Pointer(in.ImagePullSerial))
	return nil
}

func autoConvert_upstreamv1beta4_Patches_To_v1beta2_Patches(in *Patches, out *v1beta2.Patches, s conversion.Scope) error {
	out.Directory = in.Directory
	return nil
}

// Convert_upstreamv1beta4_Patches_To_v1beta2_Patches is an autogenerated conversion function.
func Convert_upstreamv1beta4_Patches_To_v1beta2_Patches(in *Patches, out *v1beta2.Patches, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_Patches_To_v1beta2_Patches(in, out, s)
}

func autoConvert_v1beta2_Patches_To_upstreamv1beta4_Patches(in *v1beta2.Patches, out *Patches, s conversion.Scope) error {
	out.Directory = in.Directory
	return nil
}

// Convert_v1beta2_Patches_To_upstreamv1beta4_Patches is an autogenerated conversion function.
func Convert_v1beta2_Patches_To_upstreamv1beta4_Patches(in *v1beta2.Patches, out *Patches, s conversion.Scope) error {
	return autoConvert_v1beta2_Patches_To_upstreamv1beta4_Patches(in, out, s)
}

func autoConvert_upstreamv1beta4_Pause_To_v1beta2_Pause(in *Pause, out *v1beta2.Pause, s conversion.Scope) error {
	out.ImageRepository = in.ImageRepository
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_upstreamv1beta4_Pause_To_v1beta2_Pause is an autogenerated conversion function.
func Convert_upstreamv1beta4_Pause_To_v1beta2_Pause(in *Pause, out *v1beta2.Pause, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_Pause_To_v1beta2_Pause(in, out, s)
}

func autoConvert_v1beta2_Pause_To_upstreamv1beta4_Pause(in *v1beta2.Pause, out *Pause, s conversion.Scope) error {
	out.ImageRepository = in.ImageRepository
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_v1beta2_Pause_To_upstreamv1beta4_Pause is an autogenerated conversion function.
func Convert_v1beta2_Pause_To_upstreamv1beta4_Pause(in *v1beta2.Pause, out *Pause, s conversion.Scope) error {
	return autoConvert_v1beta2_Pause_To_upstreamv1beta4_Pause(in, out, s)
}

func autoConvert_upstreamv1beta4_ProxyConfiguration_To_v1beta2_ProxyConfiguration(in *ProxyConfiguration, out *v1beta2.ProxyConfiguration, s conversion.Scope) error {
	out.HTTPSProxy = in.HTTPSProxy
	out.NoProxy = *(*[]string)(unsafe.Pointer(&in.NoProxy))
	return nil
}

// Convert_upstreamv1beta4_ProxyConfiguration_To_v1beta2_ProxyConfiguration is an autogenerated conversion function.
func Convert_upstreamv1beta4_ProxyConfiguration_To_v1beta2_ProxyConfiguration(in *ProxyConfiguration, out *v1beta2.ProxyConfiguration, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_ProxyConfiguration_To_v1beta2_ProxyConfiguration(in, out, s)
}

func autoConvert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_ProxyConfiguration(in *v1beta2.ProxyConfiguration, out *ProxyConfiguration, s conversion.Scope) error {
	out.HTTPSProxy = in.HTTPSProxy
	out.NoProxy = *(*[]string)(unsafe.Pointer(&in.NoProxy))
	return nil
}

// Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_ProxyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_ProxyConfiguration(in *v1beta2.ProxyConfiguration, out *ProxyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_ProxyConfiguration_To_upstreamv1beta4_ProxyConfiguration(in, out, s)
}

func autoConvert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(in *RegistryMirrorConfiguration, out *v1beta2.RegistryMirrorConfiguration, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.CACert = in.CACert
	out.Mirrors = *(*[]v1beta2.Mirror)(unsafe.Pointer(&in.Mirrors))
	return nil
}

// Convert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration is an autogenerated conversion function.
func Convert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(in *RegistryMirrorConfiguration, out *v1beta2.RegistryMirrorConfiguration, s conversion.Scope) error {
	return autoConvert_upstreamv1beta4_RegistryMirrorConfiguration_To_v1beta2_RegistryMirrorConfiguration(in, out, s)
}

func autoConvert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(in *v1beta2.RegistryMirrorConfiguration, out *RegistryMirrorConfiguration, s conversion.Scope) error {
	out.Endpoint = in.Endpoint
	out.CACert = in.CACert
	out.Mirrors = *(*[]Mirror)(unsafe.Pointer(&in.Mirrors))
	return nil
}

// Convert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration is an autogenerated conversion function.
func Convert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(in *v1beta2.RegistryMirrorConfiguration, out *RegistryMirrorConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_RegistryMirrorConfiguration_To_upstreamv1beta4_RegistryMirrorConfiguration(in, out, s)
}

func autoConvert_upstreamv1beta4_Timeouts_To_v1beta2_Timeouts(in *Timeouts, out *v1beta2.Timeouts, s conversion.Scope) error {
	// WARNING: in.ControlPlaneComponentHealthCheck requires manual conversion: does not exist in peer-type
	// WARNING: in.KubeletHealthCheck requires manual conversion: does not exist in peer-type
	// WARNING: in.KubernetesAPICall requires manual conversion: does not exist in peer-type
	// WARNING: in.EtcdAPICall requires manual conversion: does not exist in peer-type
	// WARNING: in.TLSBootstrap requires manual conversion: does not exist in peer-type
	// WARNING: in.Discovery requires manual conversion: does not exist in peer-type
	// WARNING: in.UpgradeManifests requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta2_Timeouts_To_upstreamv1beta4_Timeouts(in *v1beta2.Timeouts, out *Timeouts, s conversion.Scope) error {
	// WARNING: in.ControlPlaneComponentHealthCheckSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.KubeletHealthCheckSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.KubernetesAPICallSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.EtcdAPICallSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.TLSBootstrapSeconds requires manual conversion: does not exist in peer-type
	// WARNING: in.DiscoverySeconds requires manual conversion: does not exist in peer-type
	return nil
}
